// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYN9Mdl8gcZx25IuFEOJWGSqzPKuQcYC8',
    appId: '1:682398862823:web:e347342541a10cc44d4142',
    messagingSenderId: '682398862823',
    projectId: 'fir-zertek',
    authDomain: 'fir-zertek.firebaseapp.com',
    storageBucket: 'fir-zertek.appspot.com',
    measurementId: 'G-BMJYRRPGMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTVuzNB_-CVEbQWqnoS1kIEFxWe62DLM',
    appId: '1:682398862823:android:502d55fd795200554d4142',
    messagingSenderId: '682398862823',
    projectId: 'fir-zertek',
    storageBucket: 'fir-zertek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdOI25Q-SW-cFlEl96MS-0xoEtqaDRno',
    appId: '1:682398862823:ios:4ed11e34ac0c4b0c4d4142',
    messagingSenderId: '682398862823',
    projectId: 'fir-zertek',
    storageBucket: 'fir-zertek.appspot.com',
    iosClientId: '682398862823-0jm8qj4fu8dubebqlt0vc3jcgrk141gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseecom',
  );
}
